
---- WINDOW FUNCTION ----

--DENSE_RANK, RANK

   -- FUNCTION_NAME() OVER(ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP


	-- FUNCTION_NAME() OVER(PARTITION BY COL_NAME ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP
SELECT *, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP


-- QUERY
SELECT *, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP



-- LEAD, LAG

SELECT *, LAG(SAL, 1) OVER(ORDER BY SAL DESC) AS PREV_ROW FROM EMP
SELECT *, LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW FROM EMP

SELECT *,
LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW,
LEAD(SAL, 2) OVER(ORDER BY SAL DESC) AS NEXT2_ROW
FROM EMP






SELECT [Order Date], DATEPART(YEAR, [ORDER DATE]) AS YR, SALES FROM SALES_DATA

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date])
ORDER BY YR

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(QUARTER, [Order Date]) AS QTR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(QUARTER, [Order Date])
ORDER BY YR, QTR

--QUERY
SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(MONTH, [Order Date]) AS MON, SUM(Profit) AS TOT_PROFIT FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(MONTH, [Order Date])
ORDER BY YR, MON






 -- TEMP TABLE    
    --info that is stored for temporary period of time
	--all temp tables begins with #SYMBOL
	--stored for only one session then after closing the session it will erase the data parmenantly
	--SELECT * INTO #TABLE_VALUE FROM (QUERY) T1

SELECT * INTO #TEMP1 FROM (SELECT * FROM EMP) AB

SELECT * FROM #TEMP1

SELECT CD.ENAME, CD.EMPNO, CD.SAL INTO #TEMP2 FROM (SELECT * FROM EMP) CD

SELECT * FROM #TEMP2

SELECT * INTO #TEMP3 FROM (
 SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
 GROUP BY DATEPART(YEAR, [ORDER DATE])) T3


 SELECT *, LAG(TOT_SALES, 1) OVER(ORDER BY YR) AS PREV_YEAR_SALES FROM #TEMP3

 SELECT *, LEAD(TOT_SALES, 1) OVER(ORDER BY YR) AS NEXT_YEAR_SALES FROM #TEMP3





 -- FIRST_VALUE, LAST_VALUE

 SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT FROM SALES_DATA
 WHERE [Customer Name] = 'CLAIRE GUTE'
 ORDER BY [Order Date] ASC




  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'


  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  LAST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE] DESC) AS LAST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'



  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(PARTITION BY [CUSTOMER NAME] ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA





-- SET OPERATORS
SELECT * FROM EMP WHERE DEPTNO = 10
SELECT * FROM EMP WHERE JOB = 'CLERK'

SELECT * FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
UNION
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
INTERSECT
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
EXCEPT
SELECT * FROM EMP WHERE JOB = 'CLERK'


--QUERY
SELECT * FROM SALES_DATA WHERE Region = 'South'
INTERSECT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'


SELECT * FROM SALES_DATA WHERE Region = 'South'
EXCEPT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'
---



-- SUB QUERIES
SELECT MAX(SAL) FROM EMP

SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP)

  --get list of emp records who are working in same deptno of scott
  SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT')

  --get list of emp records whose job is same as smith
  SELECT * FROM EMP WHERE JOB = (SELECT job FROM EMP WHERE ENAME = 'SMITH')

  --get list of emp records whose sal is above avg sal
  SELECT * FROM EMP where SAL > (SELECT AVG(SAL) FROM EMP)

  --get a list of emp records who are all joined in the same year of smith
  SELECT * FROM EMP WHERE DATEPART(YEAR, HIREDATE) = (SELECT DATEPART(YEAR, HIREDATE) FROM EMP WHERE ENAME = 'SMITH')

  --get list of emp where job is same as miller or scott
  SELECT * FROM EMP WHERE JOB IN (SELECT job FROM EMP WHERE ENAME IN ('SMITH', 'MILLER'))

  --get list of emp whose deptno is same as scott, james
  SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN ('SCOTT', 'JAMES'))

 SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP

 SELECT * INTO #TEMP1 FROM (SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP) T1
 SELECT * FROM #TEMP1 WHERE ANUALL_SAL >= 30000




-- VIEWS    --an alias name for a query
            --all views are stored in databases --sql databse --view folder

CREATE VIEW VW_01 AS
(SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP)

SELECT * FROM VW_01 WHERE ANUALL_SAL >= 30000


CREATE VIEW VW_02 AS
(SELECT A.*, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO)

SELECT * FROM VW_02


ALTER VIEW VW_02 AS
(SELECT A.ENAME, A.SAL,A.EMPNO, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO)

SP_HELPTEXT VW_02




-- INDEX
	--index applied on primary key columns -- CLUSTERED INDEX
	--index applied on non primary key columns -- NONCLUSTERED INDEX

CREATE NONCLUSTERED INDEX INDEX_1 ON EMP(DEPTNO)

SP_HELP EMP

CREATE CLUSTERED INDEX INDEX_2 ON EMP(EMPNO)






-- STORED PROCEDURE
	--SET/BATCH OF SQL STATEMENTS EXECUTED ONE BY ONE

	-- CREATE PROCEDURE PROCEDURE_NAME(PARAMETERS)
	-- BEGIN
	-- STATEMENTS
	-------
	-- END


  --EX01
  CREATE PROCEDURE PR_01
  AS
  BEGIN
	SELECT * FROM EMP
	SELECT * FROM DEPT
  END
  --

  EXEC PR_01


  --EX02
  CREATE PROCEDURE PR_02
  AS
  BEGIN
	DECLARE @X INT 
	SET @X = 100
	DECLARE @Y INT
	SET @Y = 200
	PRINT @X + @Y
  END
  --

  EXEC PR_02

  -- EX03
  CREATE PROCEDURE PR_03
  AS
  BEGIN
	DECLARE @X INT 
	SET @X = 10
	SELECT * FROM EMP WHERE DEPTNO = @X
  END
  --

  EXEC PR_03


DROP PROCEDURE PR_03

--EX04
  CREATE PROCEDURE PR_04(@X INT)
  AS
  BEGIN
    SELECT * FROM EMP WHERE DEPTNO = @X
  END
  --

  EXEC PR_04 20    --20 is the value passed as @x







-- FUNCTION






-- MERGE JOIN


