select * from Customers
select * from Orders

SELECT a.customerid, a.CustomerID, a.City, b.OrderID, b.OrderDate ,
	   c.Quantity, d.ProductName, d.Price, d.Unit, e.CategoryName, f.SupplierName
FROM customers a 
left JOIN orders b			ON a.customerid = b.customerid
left JOIN OrderDetails c	on c.OrderID = b.OrderID
left join Products d		on d.ProductID = c.ProductID
LEFT JOIN Categories e		ON e.CategoryID = d.CategoryIDLEFT JOIN Suppliers f		ON f.SupplierID = d.SupplierID

-- customers a
-- orders b
-- OrderDetails c
-- Products d
-- Categories e
-- Suppliers f




--- FUNCTIONS ---		--USED TO MANIPULATE DATA
--- DATE DUNCTION ---   --CONTAINS LIST OF FUNCTION THAT CAN BE MANIPULATED/USED TO CALCULATE ON DATE COLUMNS


SELECT * FROM EMP
-- 1980-12-17 -- YEAR, MONTH, DAT, QUATER, WEEKDAY, WEEKNUM, DATEDIFF
-- DATEPART(INTERVAL, DATE_COLUMN)
SELECT HIREDATE,
DATEPART(YEAR, HIREDATE) AS YR,
DATEPART(MONTH, HIREDATE) AS MON,
DATEPART(QUARTER, HIREDATE) AS QR,
DATEPART(WEEK, HIREDATE) AS WK
FROM EMP

SELECT HIREDATE, 
DATEPART(YEAR, HIREDATE) AS YR,
DATENAME(MONTH, HIREDATE)AS MN,         --NAME
DATEPART(DAY, HIREDATE) AS DY,
DATENAME(QUARTER, HIREDATE) AS QR,
DATENAME(WEEKDAY, HIREDATE) AS WK
FROM EMP

-- DATEADD
SELECT HIREDATE,
DATEADD(YEAR, 1, HIREDATE),
DATEADD(MONTH, 1, HIREDATE) 
FROM EMP

-- DATEDIFF
SELECT [ORDER DATE], [SHIP DATE],
DATEDIFF(DAY, [ORDER DATE], [SHIP DATE]) AS DAYS_DIFF
FROM SALES_DATA

SELECT HIREDATE,
DATEDIFF(YEAR, HIREDATE, GETDATE()) AS YEARS_DIFF,
DATEDIFF(MONTH, HIREDATE, GETDATE()) AS MONTH_DIFF
FROM EMP

SELECT GETDATE()

-- EOMONTH
SELECT HIREDATE, EOMONTH(HIREDATE, 2) FROM EMP
-- 1980-12-17 -- ADD 2 MONTHS -- 1981-01-17 -- ROUND OFF TO LAST DATE -- 1981-02-28


--- SWITCHOFFSET ---       --used to convert 1 datetime zone into another datetime zone
SELECT SYSDATETIMEOFFSET()
--2025-04-28 22:18:04.4958583 +05:30

SELECT SWITCHOFFSET('2025-04-28 22:18:04.4958583 +05:30', '-10:00')   --Hawaii timezone
--2025-04-28 06:48:04.4958583 -10:00   



