---- TEXT FUCTIONS ----

 --LEN(COLNAME) -- RETURNS NO OF CHARS INCLUDE ANY APECIAL CHARS ALSO [SPACE, COMA, COLON,...]
 -- LEFT(COLNAME, NO OF CHARS)  -- RETURNS SPECIFIED NO OF CHARS FROM STARTING ONWARDS IN EACH CUSTOMER NAME
 --RIGHT(COLNAME, NO OF CHARS)  -- RETURNS SPECIFIED NO OF CHARS FROM ENDING ONWARDS IN EACH CUSTOMER NAME
  --SUBSTRING(COLNAME, NO OF CHARS)  --RETURNS SPECIFIED NO OF CHARS FROM SPECIFIED POS

SELECT [Customer NAME],
LEN ([Customer NAME]) AS LN,
LEFT([Customer Name], 4) AS FIRST_CHARS,
RIGHT([Customer Name], 6) AS LAST_CHARS,
SUBSTRING([Customer Name], 2, 4) AS FROM_SPECIFIED_POS_ONWARDS,
[Order ID] FROM SALES_DATA

--QUERY
SELECT [Customer Name],
LEN			([Order ID])			AS LN,
LEFT		([Order ID], 2)			AS FIRST_CHARS,
SUBSTRING	([Order ID], 4, 4)		AS MIDDLE_CHARS,
RIGHT		([Order ID], 6)			AS LAST_CHARS,
[Order ID] FROM SALES_DATA
--

SELECT [ORDER ID], [Customer Name],
CONCAT([ORDER ID], [Customer Name]) AS COL1,
CONCAT([ORDER ID],' : ', [Customer Name]) AS COL1,
CONCAT([ORDER ID],'  ', [Customer Name]) AS COL1
FROM SALES_DATA


  -- CHARINDEX --		used to seach a char/word in every col value and return the posision of the char/word
SELECT [Customer Name],
CHARINDEX(' ',[Customer Name], 1) AS SPACE_POS      -- shows where are all " " (space) in the col
FROM SALES_DATA

SELECT [Order ID],
CHARINDEX('2014',[Order ID], 1) AS POS_2014
FROM SALES_DATA

  -- TRIM
SELECT TRIM([CUSTOMER NAME]) AS CUST_NAME,
UPPER([CUSTOMER NAME]) AS CUST_NAME_UPER
FROM SALES_DATA


  --CASE , IIF STATEMENTS (if condition)
   -- IIF(CONDITION, TRUE_CALUE, FALSE_VALE)
   
   SELECT SALES,
   IIF(SALES>=10000, 'GRADE A', 'GRADE B') AS GRADES,
   IIF(SALES>=10000, 'GRADE A', IIF(SALES>=4000, 'GRADE B', 'GRADE C')) AS GRADES      -- nested iif
   FROM SALES_DATA
   ORDER BY SALES DESC


   SELECT PROFIT,
   IIF(profit>0, '+ PROFIT', IIF(profit=0, 'ZERO', '- PROFIT')) AS GRADES
   FROM SALES_DATA
   ORDER BY PROFIT DESC



   SELECT SALES,
   (CASE WHEN SALES <= 10000 THEN 'GRADE A' ELSE 'GRADE B' END) AS GRADES,        --kinda like a switch/like same as iif but simple syntax
   (CASE WHEN SALES <= 10000 THEN 'GRADE A' WHEN sales>4000 THEN 'GRADE B' ELSE 'GRADE C' END) AS GRADES
   FROM SALES_DATA





---- MATH FUNCTION ----

SELECT SALES, ROUND(SALES, 2) AS ROUND_SALES_1_DIGIT,		--ROUNDS UP THE VALUES , the "(SALES, 2)" 2 means max 2 digit after 0
CEILING(SALES) AS CEIL,										--ROUNDS TO CEILING
FLOOR(SALES) AS FLR											--ROUNDS TO FLOOR
FROM SALES_DATA

  --UPDATE JOIN
  SELECT * FROM EMP

CREATE TABLE EMP_NEW_SAL(EMPID    INT, NEW_SAL    NUMERIC(10, 1))INSERT INTO EMP_NEW_SAL VALUES(7369,    1200),(7499,    1450),(7521,    1700),(7566,    1950),(7654,    2200),(7698,    2450),(7782,    2700),(7788,    2950),(7839,    3200),(7844,    3450),(7876,    3700),(7900,    3950),(7902,    4200),(7934,    4450)


SELECT * FROM EMP
SELECT * FROM EMP_NEW_SAL

UPDATE EMP
SET EMP.SAL = EMP_NEW_SAL.NEW_SAL
FROM EMP INNER JOIN EMP_NEW_SAL ON EMP.EMPNO = EMP_NEW_SAL.EMPID




  --MERGE JOIN








-- WINDOW FUNCTION --

--TEMP TABLES --

-- CTE --

-- VIEWS --


