
---- WINDOW FUNCTION ----

--DENSE_RANK, RANK

   -- FUNCTION_NAME() OVER(ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP


	-- FUNCTION_NAME() OVER(PARTITION BY COL_NAME ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP
SELECT *, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP


-- QUERY
SELECT *, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP



-- LEAD, LAG

SELECT *, LAG(SAL, 1) OVER(ORDER BY SAL DESC) AS PREV_ROW FROM EMP
SELECT *, LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW FROM EMP

SELECT *,
LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW,
LEAD(SAL, 2) OVER(ORDER BY SAL DESC) AS NEXT2_ROW
FROM EMP






SELECT [Order Date], DATEPART(YEAR, [ORDER DATE]) AS YR, SALES FROM SALES_DATA

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date])
ORDER BY YR

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(QUARTER, [Order Date]) AS QTR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(QUARTER, [Order Date])
ORDER BY YR, QTR

--QUERY
SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(MONTH, [Order Date]) AS MON, SUM(Profit) AS TOT_PROFIT FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(MONTH, [Order Date])
ORDER BY YR, MON







-- FIRST_VALUE, LAST_VALUE
