--- jOINS ---   INNER/EQUI JOIN, LEFT JOIN, RIGHT JOIN, OUTER JOIN

  -- INNER/EQUI JOIN
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT * FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO   -- GIVING AN ALIA'S NAME
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO

  -- LEFT JOIN
SELECT * FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A LEFT JOIN DEPT B ON A.DEPTNO = B.DEPTNO

  -- RIGHT JOIN
SELECT * FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A RIGHT JOIN DEPT B ON A.DEPTNO = B.DEPTNO

  -- OUTER JOIN
SELECT * FROM EMP FULL JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A FULL JOIN DEPT B ON A.DEPTNO = B.DEPTNO


----QUERY----

SELECT TOP 1 * FROM SALES_DATA
SELECT TOP 1 * FROM Returns

SELECT TOP 10 A.[Order ID], A.[Order ID], A.Sales, A.[Product ID] FROM SALES_DATA A INNER JOIN Returns B ON A.[Order ID] = B.[Order ID]

SELECT TOP 10 A.[Order ID], A.[Order ID], A.Sales, A.[Product ID], b.Returned, b.[Order ID] FROM SALES_DATA A LEFT JOIN Returns B ON A.[Order ID] = B.[Order ID]
