
---- WINDOW FUNCTION ----

--DENSE_RANK, RANK

   -- FUNCTION_NAME() OVER(ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP


	-- FUNCTION_NAME() OVER(PARTITION BY COL_NAME ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP
SELECT *, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP


-- QUERY
SELECT *, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP



-- LEAD, LAG

SELECT *, LAG(SAL, 1) OVER(ORDER BY SAL DESC) AS PREV_ROW FROM EMP
SELECT *, LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW FROM EMP

SELECT *,
LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW,
LEAD(SAL, 2) OVER(ORDER BY SAL DESC) AS NEXT2_ROW
FROM EMP






SELECT [Order Date], DATEPART(YEAR, [ORDER DATE]) AS YR, SALES FROM SALES_DATA

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date])
ORDER BY YR

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(QUARTER, [Order Date]) AS QTR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(QUARTER, [Order Date])
ORDER BY YR, QTR

--QUERY
SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(MONTH, [Order Date]) AS MON, SUM(Profit) AS TOT_PROFIT FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(MONTH, [Order Date])
ORDER BY YR, MON






 -- TEMP TABLE    
    --info that is stored for temporary period of time
	--all temp tables begins with #SYMBOL
	--stored for only one session then after closing the session it will erase the data parmenantly
	--SELECT * INTO #TABLE_VALUE FROM (QUERY) T1

SELECT * INTO #TEMP1 FROM (SELECT * FROM EMP) AB

SELECT * FROM #TEMP1

SELECT CD.ENAME, CD.EMPNO, CD.SAL INTO #TEMP2 FROM (SELECT * FROM EMP) CD

SELECT * FROM #TEMP2

SELECT * INTO #TEMP3 FROM (
 SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
 GROUP BY DATEPART(YEAR, [ORDER DATE])) T3


 SELECT *, LAG(TOT_SALES, 1) OVER(ORDER BY YR) AS PREV_YEAR_SALES FROM #TEMP3

 SELECT *, LEAD(TOT_SALES, 1) OVER(ORDER BY YR) AS NEXT_YEAR_SALES FROM #TEMP3





 -- FIRST_VALUE, LAST_VALUE

 SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT FROM SALES_DATA
 WHERE [Customer Name] = 'CLAIRE GUTE'
 ORDER BY [Order Date] ASC




  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'


  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  LAST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE] DESC) AS LAST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'



  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(PARTITION BY [CUSTOMER NAME] ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA





-- SET OPERATORS
SELECT * FROM EMP WHERE DEPTNO = 10
SELECT * FROM EMP WHERE JOB = 'CLERK'

SELECT * FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
UNION
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
INTERSECT
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
EXCEPT
SELECT * FROM EMP WHERE JOB = 'CLERK'


--QUERY
SELECT * FROM SALES_DATA WHERE Region = 'South'
INTERSECT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'


SELECT * FROM SALES_DATA WHERE Region = 'South'
EXCEPT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'
---



-- SUB QUERIES
SELECT MAX(SAL) FROM EMP

SELECT * FROM EMP WHERE SAL = (SELECT MAX(SAL) FROM EMP)

  --get list of emp records who are working in same deptno of scott
  SELECT * FROM EMP WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SCOTT')

  --get list of emp records whose job is same as smith
  SELECT * FROM EMP WHERE JOB = (SELECT job FROM EMP WHERE ENAME = 'SMITH')

  --get list of emp records whose sal is above avg sal
  SELECT * FROM EMP where SAL > (SELECT AVG(SAL) FROM EMP)

  --get a list of emp records who are all joined in the same year of smith
  SELECT * FROM EMP WHERE DATEPART(YEAR, HIREDATE) = (SELECT DATEPART(YEAR, HIREDATE) FROM EMP WHERE ENAME = 'SMITH')

  --get list of emp where job is same as miller or scott
  SELECT * FROM EMP WHERE JOB IN (SELECT job FROM EMP WHERE ENAME IN ('SMITH', 'MILLER'))

  --get list of emp whose deptno is same as scott, james
  SELECT * FROM EMP WHERE DEPTNO IN (SELECT DEPTNO FROM EMP WHERE ENAME IN ('SCOTT', 'JAMES'))

 SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP

 SELECT * INTO #TEMP1 FROM (SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP) T1
 SELECT * FROM #TEMP1 WHERE ANUALL_SAL >= 30000




-- VIEWS    --an alias name for a query
            --all views are stored in databases --sql databse --view folder

CREATE VIEW VW_01 AS
(SELECT SAL, SAL*12 AS ANUALL_SAL FROM EMP)

SELECT * FROM VW_01 WHERE ANUALL_SAL >= 30000


CREATE VIEW VW_02 AS
(SELECT A.*, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO)

SELECT * FROM VW_02


ALTER VIEW VW_02 AS
(SELECT A.ENAME, A.SAL,A.EMPNO, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO)

SP_HELPTEXT VW_02




-- INDEX
	--index applied on primary key columns -- CLUSTERED INDEX
	--index applied on non primary key columns -- NONCLUSTERED INDEX

CREATE NONCLUSTERED INDEX INDEX_1 ON EMP(DEPTNO)

SP_HELP EMP

CREATE CLUSTERED INDEX INDEX_2 ON EMP(EMPNO)






-- STORED PROCEDURE
	--SET/BATCH OF SQL STATEMENTS EXECUTED ONE BY ONE

	-- CREATE PROCEDURE PROCEDURE_NAME(PARAMETERS)
	-- BEGIN
	-- STATEMENTS
	-------
	-- END


  --EX01
  CREATE PROCEDURE PR_01
  AS
  BEGIN
	SELECT * FROM EMP
	SELECT * FROM DEPT
  END
  --

  EXEC PR_01


  --EX02
  CREATE PROCEDURE PR_02
  AS
  BEGIN
	DECLARE @X INT 
	SET @X = 100
	DECLARE @Y INT
	SET @Y = 200
	PRINT @X + @Y
  END
  --

  EXEC PR_02

  -- EX03
  CREATE PROCEDURE PR_03
  AS
  BEGIN
	DECLARE @X INT 
	SET @X = 10
	SELECT * FROM EMP WHERE DEPTNO = @X
  END
  --

  EXEC PR_03


DROP PROCEDURE PR_03

--EX04
  CREATE PROCEDURE PR_04(@X INT)
  AS
  BEGIN
    SELECT * FROM EMP WHERE DEPTNO = @X
  END
  --

  EXEC PR_04 20    --20 is the value passed as @x

  --EX05
  CREATE PROCEDURE SP_01
  AS
  BEGIN
	DECLARE @X INT
	DECLARE @Y INT
	SET @X = 10
	SET @Y = 20
	PRINT @X + @Y
  END

  EXEC SP_01


  --EX06
  CREATE PROCEDURE SP_02
  AS
  BEGIN
	DECLARE @DP INT
	SET @DP = 10
	SELECT * FROM EMP WHERE DEPTNO = @DP
  END

  EXEC SP_02

  --EX07
  CREATE PROCEDURE SP_03(@X INT, @Y INT)
  AS
  BEGIN
	PRINT @X + @Y
  END

  EXEC SP_03 10, 20

  --EX08
  CREATE PROCEDURE SP_04(@X INT)
  AS
  BEGIN
  SELECT * FROM EMP WHERE DEPTNO= @X
  END

  EXEC SP_04 10

  --EX_09
  CREATE PROCEDURE SP_CHECK_EMPNO(@EMPNO INT)
  AS
  BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE EMPNO = @EMPNO)
		PRINT 'RECORDS FOUND'
	ELSE
		PRINT 'NO RECORDS FOUND'
  END

  EXEC SP_CHECK_EMPNO 778


  --EX_10
  CREATE PROCEDURE SP_CHECK_DATA(@DEPTNO INT)
  AS
  BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE DEPTNO = @DEPTNO)
		SELECT * FROM EMP WHERE DEPTNO = @DEPTNO
	ELSE
		PRINT 'NO RECORDS FOUND'
  END

EXEC SP_CHECK_DATA 60


  --EX_11
  CREATE PROCEDURE SP_CHECK_DATA_01(@DEPTNO INT)
  AS
  BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE DEPTNO = @DEPTNO)
		BEGIN
			PRINT 'RECORDS FOUND'
			SELECT * FROM EMP WHERE DEPTNO = @DEPTNO
		END
	ELSE
		PRINT 'NO RECORDS FOUND'
  END

EXEC SP_CHECK_DATA_01 10




-- LOOPS
	--WHILE
	
	--WHILE CONDITION
	--BEGIN
	--STATEMENT 1
	--STATEMENT 2
	-----
	--END


CREATE PROCEDURE LOOPS_01
AS
BEGIN
	DECLARE @X INT = 1
	DECLARE @Y INT = 10
	WHILE @X <= @Y
	BEGIN
		PRINT @X
		SET @X = @X +1
	END
END


EXEC LOOPS_01



CREATE PROCEDURE LOOPS_02
AS
BEGIN
	DECLARE @X INT = 1
	DECLARE @Y INT = 10
	WHILE @X <= @Y
	BEGIN	
		PRINT @X
		SET @X = @X +1
		IF @X = 5
			BREAK
	END
END

EXEC LOOPS_02



CREATE PROCEDURE LOOP_3(@X INT, @Y INT)
AS
BEGIN
	WHILE @X  <= @Y
	BEGIN
		IF @X %2 = 0
			PRINT @X
		SET @X = @X + 1
	END
END

EXEC LOOP_3 10, 30

DROP PROCEDURE LOOP_3




-- ERROR HANDLING
CREATE PROCEDURE ERROR_01 (@X INT, @Y INT)
AS
BEGIN
	PRINT @X/@Y
END

EXEC LOOP_04 10,2
EXEC LOOP_04 10,0


CREATE PROCEDURE ERROR_02
AS
BEGIN
	INSERT INTO EMP(EMPNO, ENAME, SAL) VALUES(9999, 'ABCDEFGHIJKL', 12000)
END

EXEC ERROR_02


SP_HELP EMP


CREATE PROCEDURE ERROR_03 (@X INT, @Y INT)
AS
BEGIN
	BEGIN TRY
		PRINT @X /@Y
	END TRY
	BEGIN CATCH
		PRINT 'ZERO ERROR DIVISION PLEASE CHECK INPUTS'
	END CATCH
END

EXEC ERROR_03 10, 0




CREATE PROCEDURE ERROR_04(@ENO INT, @ENAME VARCHAR(15), @SAL INT)
AS
BEGIN
	BEGIN TRY
		INSERT INTO EMP (EMPNO, ENAME, SAL) VALUES (@ENO, @ENAME, @SAL)
	END TRY
	BEGIN CATCH
		PRINT 'POSSIBLE ERROR IS MORE NO OF CHARS IN CHAR COLUMN'
		PRINT ERROR_MESSAGE()
	END CATCH
END

EXEC ERROR_04 8899, 'ABCD EFGH IJKL', 12000



-- TRIGGERS

-- MERGE

-- USER DEFINED FUCTION



