
---- WINDOW FUNCTION ----

--DENSE_RANK, RANK

   -- FUNCTION_NAME() OVER(ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP


	-- FUNCTION_NAME() OVER(PARTITION BY COL_NAME ORDER BY COL_NAME ASC | DESC)
SELECT * FROM EMP

SELECT *, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP
SELECT *, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP


-- QUERY
SELECT *, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS DR1 FROM EMP
SELECT *, ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP



-- LEAD, LAG

SELECT *, LAG(SAL, 1) OVER(ORDER BY SAL DESC) AS PREV_ROW FROM EMP
SELECT *, LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW FROM EMP

SELECT *,
LEAD(SAL, 1) OVER(ORDER BY SAL DESC) AS NEXT_ROW,
LEAD(SAL, 2) OVER(ORDER BY SAL DESC) AS NEXT2_ROW
FROM EMP






SELECT [Order Date], DATEPART(YEAR, [ORDER DATE]) AS YR, SALES FROM SALES_DATA

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date])
ORDER BY YR

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(QUARTER, [Order Date]) AS QTR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(QUARTER, [Order Date])
ORDER BY YR, QTR

--QUERY
SELECT DATEPART(YEAR, [ORDER DATE]) AS YR , DATEPART(MONTH, [Order Date]) AS MON, SUM(Profit) AS TOT_PROFIT FROM SALES_DATA
GROUP BY DATEPART(YEAR, [Order Date]), DATEPART(MONTH, [Order Date])
ORDER BY YR, MON






 -- TEMP TABLE    
    --info that is stored for temporary period of time
	--all temp tables begins with #SYMBOL
	--stored for only one session then after closing the session it will erase the data parmenantly
	--SELECT * INTO #TABLE_VALUE FROM (QUERY) T1

SELECT * INTO #TEMP1 FROM (SELECT * FROM EMP) AB

SELECT * FROM #TEMP1

SELECT CD.ENAME, CD.EMPNO, CD.SAL INTO #TEMP2 FROM (SELECT * FROM EMP) CD

SELECT * FROM #TEMP2

SELECT * INTO #TEMP3 FROM (
 SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
 GROUP BY DATEPART(YEAR, [ORDER DATE])) T3


 SELECT *, LAG(TOT_SALES, 1) OVER(ORDER BY YR) AS PREV_YEAR_SALES FROM #TEMP3

 SELECT *, LEAD(TOT_SALES, 1) OVER(ORDER BY YR) AS NEXT_YEAR_SALES FROM #TEMP3





 -- FIRST_VALUE, LAST_VALUE

 SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT FROM SALES_DATA
 WHERE [Customer Name] = 'CLAIRE GUTE'
 ORDER BY [Order Date] ASC




  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'


  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  LAST_VALUE([ORDER ID]) OVER(ORDER BY [ORDER DATE] DESC) AS LAST_ORDER_ID FROM SALES_DATA
  WHERE [Customer Name] = 'CLAIRE GUTE'



  SELECT [Order ID], [Order Date], [Customer Name], SALES, PROFIT,
  FIRST_VALUE([ORDER ID]) OVER(PARTITION BY [CUSTOMER NAME] ORDER BY [ORDER DATE]) AS FIRST_ORDER_ID FROM SALES_DATA





-- SET OPERATORS
SELECT * FROM EMP WHERE DEPTNO = 10
SELECT * FROM EMP WHERE JOB = 'CLERK'

SELECT * FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
UNION
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
INTERSECT
SELECT * FROM EMP WHERE JOB = 'CLERK'


SELECT * FROM EMP WHERE DEPTNO = 10
EXCEPT
SELECT * FROM EMP WHERE JOB = 'CLERK'


--QUERY
SELECT * FROM SALES_DATA WHERE Region = 'South'
INTERSECT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'


SELECT * FROM SALES_DATA WHERE Region = 'South'
EXCEPT
SELECT * FROM SALES_DATA WHERE Segment = 'Consumer'
---



-- SUB QUERIES


-- VIEWS

