---- TRIGGERS  ----
	-- special stored procedure , which executes automatically [no manual run], when an action is perfored
	-- action that can be any DDL activity on database -- DDL TRIGGER
	-- action that can be any DDL activity on database -- DML TRIGGER
	
CREATE TRIGGER TRIG_01
	ON EMP
	FOR INSERT, UPDATE
	AS 
	BEGIN
		PRINT 'NO INSERT/UPDATE IS ALLOWED'
		ROLLBACK
	END

UPDATE EMP SET SAL = 3200 WHERE EMPNO = 7788
SELECT * FROM EMP WHERE EMPNO = 7788

DROP TRIGGER TRIG_01
--


CREATE TRIGGER TRIG_02
	ON EMP
	FOR INSERT
	AS
	BEGIN
		SELECT * FROM inserted
	END

INSERT INTO EMP(EMPNO, ENAME, SAL) VALUES (1177, 'ABCD', 12000)

DROP TRIGGER TRIG_02
--


CREATE TABLE AUDIT_LOG(EMPID INT,SAL INT,DOA DATETIME)

CREATE TRIGGER TRIG_03
	ON EMP
	FOR INSERT
	AS 
	BEGIN
		INSERT INTO AUDIT_LOG SELECT EMPNO, SAL, GETDATE() FROM INSERTED
	END

INSERT INTO EMP(EMPNO, ENAME, SAL) VALUES (1177, 'ABCD', 12000)

SELECT * FROM AUDIT_LOG
SELECT * FROM EMP

DROP TRIGGER TRIG_03
--


---- FUNCTIONS ----

CREATE FUNCTION FN_01(@X INT)
  RETURNS INT
	AS 
	BEGIN
		SET @X = @X +100
		RETURN @X
	END

SELECT DBO.FN_01(100)
select sal, dbo.fn_01(sal) from emp
--

CREATE FUNCTION FN_02(@X INT)
	RETURNS VARCHAR(20)
	AS
	BEGIN
		DECLARE @Z VARCHAR(20)
		IF @X > 0
			SET @Z = 'POS'
		ELSE IF @X < 0
			SET @Z = 'NEG'
		ELSE
			SET @Z = 0
		RETURN @Z
	END

SELECT DBO.FN_02(0)
SELECT PROFIT, DBO.FN_02(PROFIT) FROM SALES_DATA
--


CREATE FUNCTION CALCULATE_AGE(@DOB DATE)
	RETURNS INT
	AS BEGIN
		RETURN DATEDIFF(YEAR, @DOB, GETDATE())
	END

SELECT DBO.CALCULATE_AGE('01-JAN-1980')
--

-- INLINE TABLE VALUED FUNCTIONS
CREATE FUNCTION GET_DEPT_DATE(@DEPTNO INT)
	RETURNS TABLE
	AS
		RETURN (SELECT * FROM EMP WHERE DEPTNO = @DEPTNO)

SELECT * FROM DBO.GET_DEPT_DATE(20)
---------------------


---- MERGE ----

CREATE TABLE EMP_NEW_01(EMPID INT, SAL INT)
INSERT INTO EMP_NEW_01 VALUES(7654,    18000),(7698,    20000),(7782,    22000),(7788,    24000),(9999,    12000),(8888,    13000)MERGE EMP AS TARGETUSING EMP_NEW_01 AS SOURCEON TARGET.EMPNO = SOURCE.EMPIDWHEN MATCHED THEN     UPDATE SET TARGET.SAL = SOURCE.SALWHEN NOT MATCHED THEN    INSERT (EMPNO, SAL) VALUES (SOURCE.EMPID, SOURCE.SAL);

SELECT * FROM EMP


SP_HELP EMP
