-- 
CREATE PROCEDURE SP_01
AS
BEGIN
	DECLARE @X INT 
	DECLARE @Y INT
	SET @X = 10
	SET @Y = 20
	PRINT @X + @Y
END

EXEC SP_01
--
CREATE PROCEDURE SP_02
AS
BEGIN
	DECLARE @DP INT
	SET @DP = 10
	SELECT * FROM EMP WHERE DEPTNO = @DP
END

EXEC SP_02
--
CREATE PROCEDURE SP_03(@X INT, @Y INT)
AS
BEGIN
	PRINT @X + @Y
END

EXEC SP_03 30, 20
-- CREATE A SP WITH NAME AS SP_04 WITH 1 INPUT PARAMATER DEPTNO  & PRINT ALL RECORDS BELONGS TO INPUT PARAMETER
CREATE PROCEDURE SP_04 (@DEPTNO INT )AS BEGINSELECT * FROM EMP WHERE DEPTNO = @DEPTNOEND 

EXEC SP_04 10

-- IF ELSE CONDITION
CREATE PROCEDURE SP_CHECK_EMPNO(@EMPNO INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE EMPNO = @EMPNO)
		PRINT 'RECORDS FOUND'
	ELSE
		PRINT 'NO RECORDS FOUND'
END

EXEC SP_CHECK_EMPNO 778
--
CREATE PROCEDURE SP_CHECK_DATA(@DEPTNO INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE DEPTNO = @DEPTNO)
		SELECT * FROM EMP WHERE DEPTNO = @DEPTNO
	ELSE
		PRINT 'NO RECORDS FOUND'
END

EXEC SP_CHECK_DATA 60
--
CREATE PROCEDURE SP_CHECK_DATA_01(@DEPTNO INT)
AS
BEGIN
	IF EXISTS(SELECT * FROM EMP WHERE DEPTNO = @DEPTNO)
	BEGIN
		PRINT 'RECORDS FOUND'
		SELECT * FROM EMP WHERE DEPTNO = @DEPTNO
	END
	ELSE
		PRINT 'NO RECORDS FOUND'		
END
-- LOOPS
-- EXECUTING BLOCK OF STATEMENTS MULTIPLE NO OF TIMES.
-- WHILE
-- FOR EACH -- DO NOT DISCUSS
-- WHILE CONDITION
-- BEGIN
-- STATEMENT1
-- STATEMENT2
-------
-- END

CREATE PROCEDURE LOOPS_01
AS
BEGIN
	DECLARE @X INT = 1
	DECLARE @Y INT = 10
	WHILE @X <= @Y
	BEGIN
		PRINT @X
		SET @X = @X + 1
	END
END

EXEC LOOPS_01
--
CREATE PROCEDURE LOOPS_02
AS
BEGIN
	DECLARE @X INT = 1
	DECLARE @Y INT = 10
	WHILE @X <= @Y
	BEGIN
		PRINT @X
		SET @X = @X + 2
	END
END

EXEC LOOPS_02
--
CREATE PROCEDURE LOOPS_03
AS
BEGIN
DECLARE @X INT = 1
	DECLARE @Y INT = 10
	WHILE @X <= @Y
	BEGIN
		PRINT @X
		SET @X = @X +1
		IF @X = 5
			BREAK		
	END
END
EXEC LOOPS_03

-- CREATE PROCEDURE WITH 2 INPUT PARAMTERES X, Y  , LOOPS START FROM X TO Y & PRINT ONLY EVEN NUMBERS
ALTER PROCEDURE LOOPS_04(@X INT, @Y INT)
AS
BEGIN
	WHILE @X <= @Y
	BEGIN
		IF @X %2 =0
			PRINT @X
		SET @X = @X + 1
	END
END

EXEC LOOPS_04 10, 30

-- ERROR HANDLING
CREATE PROCEDURE ERROR_01(@X INT, @Y INT)
AS
BEGIN
	PRINT @X/@Y
END

EXEC LOOPS_05 10, 2
EXEC LOOPS_05 10, 0

ALTER PROCEDURE ERROR_02
AS
BEGIN
	INSERT INTO EMP(EMPNO, ENAME, SAL) VALUES(9999, 'ABCDEFGHIJKLOP', 12000)
END

EXEC ERROR_02

SP_HELP EMP

-- 
CREATE PROCEDURE ER_01(@X INT, @Y INT)
AS
BEGIN
	BEGIN TRY
		PRINT @X /@Y
	END TRY
	BEGIN CATCH
		PRINT 'ZERO ERROR DIVISION PLEASE CHECK INPUTS'
	END CATCH
END

EXEC ER_01 10, 0
--
CREATE PROCEDURE ER_02(@ENO INT, @ENAME VARCHAR(15), @SL INT)
AS
BEGIN
	BEGIN TRY
		INSERT INTO EMP (EMPNO, ENAME, SAL) VALUES (@ENO, @ENAME, @SL)
	END TRY
	BEGIN CATCH
		PRINT 'POSSIBLE ERROR IS MORE NO OF CHARS IN CHAR COLUMN'
		PRINT ERROR_MESSAGE()
	END CATCH
END

EXEC ER_02 8899, 'ABCD EFGH IJKL', 12000

-- TRIGGERS
-- MERGE
-- USER DEFINED FUNCTIONS
