-- DML COMMANDS
-- UPDATE

UPDATE EMP_DATA SET EMP_NAME = 'TESTB' WHERE EMP_ID = 'A1102'
SELECT * FROM EMP_DATA

UPDATE EMP_DATA SET EMP_NAME = 'TESTD', EMP_EMAILID = 'ABCD1@GMAIL.COM' WHERE EMP_ID = 'A1104'
SELECT * FROM EMP_DATA

UPDATE EMP_DATA SET EMP_DOJ = '01-FEB-2025'
SELECT * FROM EMP_DATA

-- UPDATE EMP_lOC AS BANGALORE FOR ALL RECORDS WITH NULL VALUE
UPDATE EMP_DATA SET EMP_LOC = 'BANGALORE' WHERE EMP_LOC IS NULL
SELECT * FROM EMP_DATA

-- UPDATE EMP_EMAILID AS NULL FOR EMP_ID A1101
UPDATE EMP_DATA SET EMP_EMAILID = NULL WHERE EMP_ID = 'A1101'

-- DELETE
DELETE FROM EMP_DATA WHERE EMP_ID = 'A1101'
SELECT * FROM EMP_DATA

DELETE FROM EMP_DATA

-- CONSTRAINTS OR RULES
-- USED TO RESTRICT THE DATA/VALUES WHILE INSERTING THE DATA INTO A TABLE
-- UNIQUE    -- WILL NOT ALLOW DUPLICATES INTO A COLUMN
-- NOT NULL  -- WILL STOP ENTERING NULL VALUES INTO A COLUMN
CREATE TABLE EMP_DATA_01
(EMP_ID		CHAR(5) UNIQUE, EMP_NAME	VARCHAR(20) NOT NULL, DOJ	DATE, SAL	NUMERIC(8,1))

INSERT INTO EMP_DATA_01 VALUES('A1101', 'TESTA', '01-JAN-2025', 9000)
INSERT INTO EMP_DATA_01 VALUES('A1102', 'TESTA', '01-JAN-2025', 9000)
INSERT INTO EMP_DATA_01 VALUES('A1102', NULL, '01-JAN-2025', 9000)
SELECT * FROM EMP_DATA_01
--
-- CHECK -- IS USED TO ADD CONDITION BASED RULES ON A COL (>, <, >=, <=..)
CREATE TABLE EMP_DATA_02
(
EMPID		CHAR(5)     NOT NULL  UNIQUE, 
ENAME       VARCHAR(40) NOT NULL,  
DOJ         DATE        CHECK(DOJ >='01-JAN-2025'),
SAL			INT			CHECK(SAL >= 15000)
)
INSERT INTO EMP_DATA_02 VALUES ('A1101', 'ABCD', '01-JAN-2025', 15000)

-- CREATE A TABLE WITH NAME AS CONS_01
-- STUD_ID    -- FIXED 6 CHARS           -- NO DUPLICATES , NO NULLS
-- STUD_NAME  -- VARIABLE UPTO 60 CHARS  -- NO NULLS
-- STUD_FEES  -- TOT NO OF DIGITS ARE 8 WITH 1 DECIMALS -- FEES > 15000

-- PROVIDE AN INSERT VIOLATING STUD_FEES CONDITION
CREATE TABLE CONS_01(STUD_ID CHAR(6) UNIQUE NOT NULL , STUD_NAME VARCHAR(60) NOT NULL ,STUD_FEES NUMERIC(8,1) CHECK(STUD_FEES  >15000))INSERT INTO CONS_01 VALUES('A11001','TESTA',14000)
--
-- PRIMARY KEY -- STOP NULL VALUES/DUPLICATES 
-- DEFAULT     -- WHEN COL VALUE NOT SUPPLIED INSTEAD OF TAKING NULL AS DEFAULT , NEEDED SOME OTHER VALUES AS DEFAULT

CREATE TABLE EMP_DATA_03
(
EMPID	INT		PRIMARY KEY,
ENAME	VARCHAR(50),
CITY	VARCHAR(20) DEFAULT 'BANGALORE'
)

INSERT INTO EMP_DATA_03 VALUES(11, 'ABCD', 'PUNE')
INSERT INTO EMP_DATA_03(EMPID, ENAME) VALUES(12, 'EFGH')
SELECT * FROM EMP_DATA_03

-- FOREIGN KEY 
CREATE TABLE EMP_001
(EMPID INT PRIMARY KEY, ENAME VARCHAR(20))
INSERT INTO EMP_001 VALUES(11, 'A')
INSERT INTO EMP_001 VALUES(12, 'B')
INSERT INTO EMP_001 VALUES(13, 'C')

CREATE TABLE EMP_TRANSACTIONS
(EMP_ID INT FOREIGN KEY REFERENCES EMP_001(EMPID) , SAL INT, MON VARCHAR(20))
INSERT INTO EMP_TRANSACTIONS VALUES (11, 10000, 'JAN')
INSERT INTO EMP_TRANSACTIONS VALUES (11, 10000, 'FEB')
INSERT INTO EMP_TRANSACTIONS VALUES (15, 10000, 'JAN')

SELECT * FROM EMP_TRANSACTIONS
