-- NOTE: COMMANDS OR NAMES CAN BE TYPED IN UPPER/LOWER/MIXED CASE ALPHABETS
-- NOTE: SQL COMMANDS ARE NOT CASE SENSITIVE

-- DQL 
-- DATA QUERY LANGUAGE
-- SELECT
-- SELECT * FROM TABLE_NAME

SELECT * FROM EMP 
SELECT EMPNO, ENAME, SAL FROM EMP

-- WHERE STATEMENT
-- IS USED TO APPLY FILTER ON SELECT STATEMENT
SELECT * FROM EMP WHERE DEPTNO = 10
SELECT * FROM EMP WHERE DEPTNO = 10 OR DEPTNO = 20 

SELECT * FROM EMP WHERE ENAME = 'SMITH'
SELECT * FROM EMP WHERE ENAME = 'SMITH' OR ENAME = 'SCOTT'

-- GET LIST OF EMP WHERE JOB IS ANALYST
SELECT * FROM EMP WHERE JOB = 'ANALYST'

-- GET LIST OF EMP WHERE EMPNO IS 7788 OR 7369
SELECT * FROM EMP WHERE EMPNO = 7788 OR EMPNO = 7369

SELECT * FROM EMP WHERE SAL >=3000
SELECT * FROM EMP WHERE SAL >=1000 AND SAL <=3000

SELECT * FROM EMP WHERE HIREDATE >='01-JAN-1982'
SELECT * FROM EMP WHERE HIREDATE >='01-JAN-1982' AND HIREDATE<='31-DEC-1982'

-- DD-MMM-YYYY, MM-DD-YYYY, MM/DD/YYYY, MM.DD.YYYY
-- MMM MEANING MONTH IN TEXT FORMAT -- JAN, FEB, 
-- MM MEANING MONTH IN NUMBER FORMAT -- 01, 02..

-- IF TABLE_NAMES/COL_NAME ARE IN RED COLORED UNDERLINE [MEANING SYSTEM NOT IDENTIFYING THE LATEST TABLE CREATED]
-- CLICK ANYWHERE IN QUERY WINDOW -- GOTO EDIT MENU -- SELECT OPTION INTELLISENSE -- CLICK ON REFRESH LOCAL CACHE

-- TO SAVE QUERY WINDOW 
-- GOTO FILE MENU -- SELECT SAVE -- BROWSE FOR THE LOCATION TO SAVE

-- GOTO TOOLS MENU 
-- SELECT OPTIONS
-- IN LEFT SIDE PANE -- EXPAND TEXT EDITOR -- SELECT ALL LANGUAGES -- IN RIGHT SIDE PANE -- PUT TICK MARK FOR LINE NUMBERS OPTION
