-- GROUP BY
-- SUMMARY REPORTS/MIS REPORTS
SELECT DEPTNO, COUNT(*) AS RECORDS_CNT FROM EMP
GROUP BY DEPTNO

SELECT JOB, COUNT(*) AS CNT_ROWS FROM EMP
GROUP BY JOB

SELECT EMPNO , COUNT(*) AS EMP_CNT FROM EMP
GROUP BY EMPNO

-- AGGREGATIONS
-- COUNT(*) -- ROW COUNT, SUM(COL_NAME) , MAX(COL_NAME), MIN(COL_NAME, AVG(COL_NAME)

SELECT DEPTNO, COUNT(*) AS RW_CNT, SUM(SAL) AS TOTAL_SAL FROM EMP
GROUP BY DEPTNO

-- JOB WISE COUNT ROWS, MAX OF SAL IN EACH JOB
SELECT JOB, COUNT(*) AS ROW_CNT, MAX(SAL) AS MX_SAL FROM EMP
GROUP BY JOB

-- DEPTNO WISE AVG(SAL) FOR EACH DEPTNO, MAX(SAL) IN EACH DEPTNO
SELECT DEPTNO, AVG(SAL) AS AVG_SAL, MAX(SAL) AS MX_SAL FROM EMP
GROUP BY DEPTNO

-- ORDER BY 
-- IS USED TO SORT SELECT STATEMENT OUTPUT BASED ON A COL ASC|DESC
SELECT * FROM EMP ORDER BY SAL DESC

SELECT * FROM EMP ORDER BY SAL 
-- MULTI COL GROUP BY
SELECT * FROM EMP ORDER BY DEPTNO

SELECT DEPTNO, JOB, COUNT(*) AS REC_CNT FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO

SELECT DEPTNO, JOB, SUM(SAL) AS TOT_SAL FROM EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO

-- HOW TO IMPORT EXCEL DATA TO SQL SERVER
-- GOTO LINK AS BELOW OR FROM CHAT WINDOW
-- https://drive.google.com/drive/folders/1BbB3TYUQp5N5eP30-CGO755XDLlKe1Fq?usp=drive_link
-- DOWNLOAD SAMPLE-SUPERSTORE.XLS
-- DO NOT OPEN IT 

-- RIGHT CLICK ON DATABASE [SQL CLASSES] -- SELECT OPTION TASKS 
                                         -- UNDER TASKS 
										 -- SELECT IMPORT DATA
-- THIS WILL OPEN A WINDOW WELCOME TO SQL SERVER IMPORT AND EXPORT WIZARD

-- AFTER LOADING DATA OR CREATING NEW TABLES ALWAYS PERFORM BELOW 2 STEPS EVERY TIME
-- PLACE CURSOR ANYWHERE IN QUERY WINDOW
-- EDIT MENU -- INTELLISENSE -- REFRESH LOCAL CACHE
-- SELECT SQL SERVER DATABASE -- RIGHT CLICK REFRESH

SELECT * FROM SALES_DATA
SELECT [CUSTOMER NAME], COUNT(*) ORDERS_CNT FROM SALES_DATA
GROUP BY [CUSTOMER NAME]
ORDER BY ORDERS_CNT ASC

SELECT REGION, COUNT(*) AS CNT_ORDERS, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY Region

-- STATE WISE HOW MANY ORDERS, TOT SALES, TOT PROFIT
SELECT STATE, COUNT([ORDER ID]) AS CNT_ORDERS FROM SALES_DATA
GROUP BY STATE

-- SHIP MODE HOW MANY ORDERS
SELECT [SHIP MODE], COUNT(*) AS ORDERS_CNT FROM SALES_DATA
GROUP BY [SHIP MODE]

-- CUSTOMER NAME CONTAINS SPACE USE SQUARE BRACKETS []

-- FOR PEOPLE WHO ARE NOT ABLE TO IMPORT EXCEL FILE 
-- GOTO LINK BELOW OR FROM CHAT WINDOW
-- https://drive.google.com/drive/folders/1BbB3TYUQp5N5eP30-CGO755XDLlKe1Fq?usp=drive_link
-- DOWNLOAD SALESORDER_SCRIPT.SQL
-- DOUBLE CLICK ON THE FILE AFTER DOWNLOADING
-- CHECK QUERY SALSORDER SCRIPT -- POINTED TO SQL CLASS DATABASE
-- CLICK ON EXECUTE BUTTON 1 TIME ONLY

SELECT CATEGORY, [SUB-CATEGORY], SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY Category, [Sub-Category]
ORDER BY Category

-- FOR EACH STATE , CITY WISE COUNT NO OF ORDER ID, TOT PROFIT
SELECT STATE, CITY, COUNT([ORDER ID]) AS CNT_ORDERS , SUM(PROFIT) AS TOT_PROFIT FROM SALES_DATA
GROUP BY STATE, CITY
ORDER BY STATE

-- FOR EACH REGION, SHIP MODE COUNT NO OF ORDER ID
SELECT REGION, [SHIP MODE], COUNT([ORDER ID]) AS ORDERS_CNT FROM SALES_DATA
GROUP BY REGION, [SHIP MODE]
ORDER BY REGION

-- FOR EACH REGION, SEGMENT COUNT ORDER ID, TOT PROFIT
SELECT REGION, SEGMENT, COUNT(*) AS ORDER_CNT, SUM(PROFIT) AS TOTAL_PROFIT FROM SALES_DATAGROUP BY Region, SegmentORDER BY Region

-- DDL COMMANDS
-- DML COMMANDS
