-- WINDOW FUNCTIONS
-- FUNCTION_NAME() OVER(ORDER BY COL_NAME ASC | DESC)

SELECT *, DENSE_RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP
SELECT *, RANK() OVER(ORDER BY SAL DESC) AS R1 FROM EMP

-- FUNCTION_NAME() OVER(PARTITION BY COL_NAME ORDER BY COL_NAME ASC | DESC)
SELECT *, DENSE_RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP
SELECT *, RANK() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP

-- REPLACE DENSE_RANK() WITH ROW_NUMBER() IN BOTHE PLACES WITH PARTITION & W/O PARTITION STATEMENTS
SELECT *, ROW_NUMBER() OVER(ORDER BY SAL DESC) AS R1 FROM EMP
SELECT *, ROW_NUMBER() OVER(PARTITION BY DEPTNO ORDER BY SAL DESC) AS T1 FROM EMP

-- LEAD, LAG
SELECT *, 
LAG(SAL, 1)OVER(ORDER BY SAL DESC) AS PREV_ROW, 
LAG(SAL, 2)OVER(ORDER BY SAL DESC) AS PREV_ROW 
FROM EMP

SELECT *, 
LEAD(SAL, 1)OVER(ORDER BY SAL DESC) AS NEXT_ROW, 
LEAD(SAL, 2)OVER(ORDER BY SAL DESC) AS NEXT_ROW 
FROM EMP

SELECT [ORDER DATE], DATEPART(YEAR, [ORDER DATE]) AS YR, SALES FROM SALES_DATA

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [ORDER DATE])
ORDER BY YR

SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, DATEPART(QUARTER, [ORDER DATE]) AS QTR , SUM(SALES) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [ORDER DATE]) , DATEPART(QUARTER, [ORDER DATE]) 
ORDER BY YR, QTR

-- MAKE REPORT YR, MONTH SUM PROFIT
SELECT DATEPART(YEAR, [ORDER DATE]) AS YR, DATEPART(MONTH, [ORDER DATE]) AS MON , SUM(PROFIT) AS TOT_SALES FROM SALES_DATA
GROUP BY DATEPART(YEAR, [ORDER DATE]) , DATEPART(MONTH, [ORDER DATE]) 
ORDER BY YR, MON

-- FIRST_VALUE, LAST_VALUE
