-- DDL COMMANDS
-- DATA DEFINITION LANGUAGE
-- CREATE, ALTER, DROP, TRUNCATE

-- CREATE -- COMMAND USED TO CREATE ANY DATABASE OBJECT IN THE DATABASE
-- CREATE TABLE TABLE_NAME
-- (COL_NAM1   DATATYPE1, COL_NAME2  DATATYPE2, COL_NAM3  DATATYPE3........)
-- WHAT IS DATATYPE?
-- TYPE OF INFORMATION 

CREATE TABLE STUDENTS
(STUD_ID    CHAR(6), STUD_NAME	 VARCHAR(50), DOJ  DATE, LOC  VARCHAR(30), FEES   INT)

-- EMPLOYEE
-- EMP_ID     -- FIXED 5 CHARS
-- EMP_NAME   -- VARIABLE IN LENGTH OF UPTO 100 CHARS
-- EMP_DOJ    -- DATE
-- EMP_CITY   -- VARIABLE IN LENGTH OF UPTO 20 CHARS
-- PINCODE    -- 7 DIGITS [NO DECIMALS]

CREATE TABLE EMPLOYEE
(EMP_ID   CHAR(5), EMP_NAME   VARCHAR(100),  EMP_DOJ   DATE, EMP_CITY  VARCHAR(20),  PINCODE   INT)

-- CHAR         -- FIXED NO OF CHARS			EG: CHAR(5)		[FIXED IN LENGT OF CHARS]
-- VARCHAR      -- VARIABLE IN LENGTH OF CHAR	EG: VARCHAR(20) [NO OF CHARS CAN BE RANGED FROM 1 TO 20]
-- INT          -- NO DECIMALS, NO LENGTH       EG: INT
-- DATE         -- ONLY DATE VALUES, NO LENGTH  EG: DATE
-- NUMERIC      -- NUMBERS WITH FIXED DECIMALS  EG: NUMERIC(6, 1) -- [TOT NO OF DIGITS ARE 6 , NO OF FIXED DECIMALS ARE 1]
                                                 -- NUMERIC(6, 1) -- 123.4, 1234.5, 12345.2, 1234.4
												 -- NUMERIC(10, 2) --
-- DECIMALS     -- SIMILAR TO NUMERIC DATA TYPE

SP_HELP STUDENTS

SP_HELP EMPLOYEE

-- ALTER COMMAND
ALTER TABLE EMPLOYEE ADD EMP_EMAILID  VARCHAR(80)
SP_HELP EMPLOYEE
SELECT * FROM EMPLOYEE

ALTER TABLE EMPLOYEE DROP COLUMN PINCODE
SP_HELP EMPLOYEE
SELECT * FROM EMPLOYEE

ALTER TABLE EMPLOYEE ALTER COLUMN EMP_NAME VARCHAR(60)
SP_HELP EMPLOYEE

SP_RENAME 'EMPLOYEE.EMP_CITY', 'EMP_LOC'

SP_RENAME 'EMPLOYEE', 'EMP_DATA'

SP_HELP EMP_DATA

-- DROP
DROP TABLE EMP_DATA 
-- REMOVE ALL DATA & TABLE FROM DATABASE PERMANENTLY

-- DML COMMANDS
-- DATA MANIPULATION LANGUAGE 
-- INSERT, UPDATE, DELETE

SP_HELP EMP_DATA
INSERT INTO EMP_DATA VALUES('A1101', 'TESTA', '01-JAN-2025', 'PUNE', 'ABCD@GMAIL.COM')
INSERT INTO EMP_DATA VALUES('A1102',  NULL, '01-FEB-2025', 'BANG', NULL)

INSERT INTO EMP_DATA(EMP_ID, EMP_NAME) VALUES('A1103', 'TESTC')
INSERT INTO EMP_DATA(EMP_ID, EMP_LOC) VALUES('A1104', 'DELHI')

SELECT * FROM EMP_DATA