-- JOINS
-- INNER JOIN
SELECT * FROM EMP INNER JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO  
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A INNER JOIN DEPT B ON A.DEPTNO = B.DEPTNO

-- LEFT JOIN
SELECT * FROM EMP LEFT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A LEFT JOIN DEPT B ON A.DEPTNO = B.DEPTNO

-- RIGHT JOIN
SELECT * FROM EMP RIGHT JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A RIGHT JOIN DEPT B ON A.DEPTNO = B.DEPTNO

-- FULL JOIN
SELECT * FROM EMP FULL JOIN DEPT ON EMP.DEPTNO = DEPT.DEPTNO
SELECT A.ENAME, A.EMPNO, A.SAL, B.DNAME, B.LOC FROM EMP A FULL JOIN DEPT B ON A.DEPTNO = B.DEPTNO

--
SELECT TOP 1 * FROM SALES_DATA
SELECT TOP 1 * FROM Returns
-- EG: SALES_DATA -- ORDERS AS 11, 12, 13, 14
-- RETURNS -- ORDERS AS 12, 15

-- GET ORDER IDS MATCHED BETWEEN BOTH TABLES [ORDER ID], [CUSTOMER ID], SALES, PROFIT
SELECT SO.[Order ID], SO.[Customer ID], SO.Sales, SO.Profit FROM SALES_DATA SO INNER JOIN Returns RT ON SO.[Order ID] = RT.[Order ID]

-- GET ALL ORDER ID'S ONLY FROM SALES DATA EVEN IF THERE IS NO MATCH WITH RETURNS [ORDER ID], [CUSTOMER ID], SALES, PROFIT, FROM RETURNS TABLE -- RETURNED, ORDER ID
SELECT SO.[Order ID], SO.[Customer ID], SO.Sales, SO.Profit, RT.[Order ID], RT.Returned FROM SALES_DATA SO LEFT JOIN Returns RT ON SO.[Order ID] = RT.[Order ID]



