-- MULTI TABLE JOINS

----- PROCEDURE 1
-- IMPORT DATABASE.XLS FILE
-- GOTO LINK BELOW 
-- https://drive.google.com/drive/folders/1BbB3TYUQp5N5eP30-CGO755XDLlKe1Fq?usp=drive_link
-- DOWNLOAD DATABASE.XLS FILE

-- HOW TO IMPORT EXCEL TO DATABASE 
-- IMPORT_STEPS.DOCX 
-- DO NOT SELECT EXCEL SHEETS ENDNG WITH UNDERSCORE & SHEET1, SHEET2..

----- PROCEDURE 2
-- GOTO LINK BELOW
-- https://drive.google.com/drive/folders/1BbB3TYUQp5N5eP30-CGO755XDLlKe1Fq?usp=drive_link
-- DOWNLOAD FILE DATABASESCRIPT.SQL FILE
-- OPEN DATABASESCRIPT.SQL FILE -- POINT TO SQL CLASSES DATABASE -- CLICK ON EXECUTE 1 TIME 

-- EITHER PROCEDURE1 OR PROCEDURE2 FOLLOW

-- 2STEPS REFRESH
-- SELECT DATABASE -- CLICK ON REFRESH
-- SELECT ANYWHERE IN QUERY WINDOW -- GOTO EDIT -- INTELLISENSE -- REFRESH LOCAL CACHE

SELECT A.CustomerID, A.CustomerName, A.City, B.OrderID, B.OrderDate, C.Quantity,
D.ProductName, D.Price, D.Unit, E.CategoryName, F.SupplierName
FROM Customers$ A 
LEFT JOIN Orders$ B ON A.CustomerID = B.CustomerID
LEFT JOIN OrderDetails$ C ON C.OrderID = B.OrderID
LEFT JOIN Products$ D ON D.ProductID = C.ProductID
LEFT JOIN Categories$ E ON E.CategoryID = D.CategoryID
LEFT JOIN Suppliers$ F ON F.SupplierID = D.SupplierID

-- FUNCTIONS
-- USED TO MANIPULATE WITH DATA 
-- DATE FUNCTIONS 
-- CONTAIN LIST OF FUNCTIONS THAT CAN BE MANIPULATED/USED TO CALCULATES ON DATE COLUMNS

SELECT * FROM EMP
-- 1980-12-17 
-- INTERVAL -- YEAR, MONTH, DAY, QUARTER, WEEKDAY, WEEKNUM
-- DATEPART(INTERVAL, DATE_COLUMN)
SELECT HIREDATE, 
DATEPART(YEAR, HIREDATE) AS YR,
DATEPART(MONTH, HIREDATE) AS MON,
DATEPART(DAY, HIREDATE) AS DY,
DATEPART(QUARTER, HIREDATE) AS QR,
DATEPART(WEEKDAY, HIREDATE) AS WK
FROM EMP

-- REPLACE DATERART WITH DATENAME
-- DATENAME(INTERVAL, DATE_COL)

SELECT HIREDATE, 
DATENAME(YEAR, HIREDATE) AS YR,
DATENAME(MONTH, HIREDATE) AS MON,
DATENAME(DAY, HIREDATE) AS DY,
DATENAME(QUARTER, HIREDATE) AS QR,
DATENAME(WEEKDAY, HIREDATE) AS WK
FROM EMP

-- DATEADD
SELECT HIREDATE, 
DATEADD(YEAR, 1, HIREDATE),
DATEADD(MONTH, 1, HIREDATE) FROM EMP

-- DATEDIFF
SELECT [ORDER DATE], [SHIP DATE],
DATEDIFF(DAY, [ORDER DATE], [SHIP DATE]) AS DAYS_DIFF
FROM SALES_DATA

SELECT HIREDATE, 
DATEDIFF(YEAR, HIREDATE, GETDATE()) AS YEARS_DIFF,
DATEDIFF(MONTH, HIREDATE, GETDATE()) AS YEARS_DIFF FROM EMP

SELECT GETDATE()

-- EOMONTH
SELECT HIREDATE, EOMONTH(HIREDATE, 2) FROM EMP
-- 1980-12-17 -- ADD 2 MONTHS -- 1981-02-17 -- ROEUND OFF TO LAST DATE -- 1981-02-28

-- SWITCHOFFSET
-- USED TO CONVERT 1 DATETIME ZONE  INTO ANOTHER DATETIME ZONE
SELECT SYSDATETIMEOFFSET()
-- 2025-04-28 22:17:46.0490054 +05:30

SELECT SWITCHOFFSET('2025-04-28 22:17:46.0490054 +05:30', '-10:00')
