-- TEXT FUNCTIONS
-- LEN(COLUMN_NAME)                  -- RETURNS NO OF CHARS INCLUDE ANY SPECIAL CHARS ALSO [SPACE, COMMA, COLON,...]
-- LEFT(COLUMN_NAME, NO OF CHARS)    -- RETURNS SPECIFIED NO OF CHARS FROM STARTING ONWARDS IN EACH CUSTOMER NAME
-- RIGHT(COLUMN_NAME, NO OF CHARS)   -- RETURNS SPECIFIED NO OF CHARS FROM ENDING ONWARDS IN EACH CUSTOMER NAME
-- SUBSTRING(COL_NAME, START_POS, NO_OF_CHARS) -- RETURNS SPECIFIED NO OF CHARS FROM SPCIFIED POS
SELECT [CUSTOMER NAME], 
LEN([CUSTOMER NAME]) AS LN,
LEFT([CUSTOMER NAME], 4) AS FIRST_CHARS,
RIGHT([CUSTOMER NAME], 6) AS LAST_CHARS,
SUBSTRING([CUSTOMER NAME], 2, 4) AS FROM_SPCIFIC_POS_ONWARDS,
[ORDER ID]  FROM SALES_DATA

-- CA-2016-152156 - CA, 2016, 152156
SELECT [ORDER ID], LEFT([ORDER ID], 2) AS CNTRY_CODE, SUBSTRING([ORDER ID], 4, 4) AS YR,
RIGHT([ORDER ID], 6) AS ORDER_ID FROM SALES_DATA

SELECT [ORDER ID], [CUSTOMER NAME],
CONCAT([ORDER ID], [CUSTOMER NAME]) AS CON1,
CONCAT([ORDER ID], ' : ', [Customer Name]) AS CON2,
CONCAT([ORDER ID], '  ', [Customer NAME], ' ', SALES) AS CON3
FROM SALES_DATA

-- CHARINDEX -- USED TO SEARCH FOR A CHAR/WORD IN EVERY COL VALUE AND RETURNS POS OF THE CHAR/WORD 
SELECT [CUSTOMER NAME], CHARINDEX(' ',[CUSTOMER NAME], 1) AS SPACE_POS FROM SALES_DATA
SELECT [ORDER ID], CHARINDEX('2014',[ORDER ID], 1) AS POS_2014 FROM SALES_DATA

SELECT TRIM([CUSTOMER NAME]) AS CUST_NAME, UPPER([CUSTOMER NAME]) AS CUST_NAME_UPER FROM SALES_DATA

-- CASE , IIF STATEMENTS
-- IIF(CONDITION, TRUE_VALUE, FALSE_VALUE)
-- IIF(2>3, A, B)
SELECT SALES, 
IIF(SALES>=10000, 'GRADE A', 'GRADE B') AS GRADES ,
IIF(SALES>=10000, 'GRADE A', IIF(SALES>=4000, 'GRADE B', 'GRADE C')) AS GRADES FROM SALES_DATA
ORDER BY SALES DESC

-- PROFIT >0 POS_PROFIT, 0 - ZERO, <0 - NEG PROFIT
SELECT PROFIT, IIF(PROFIT > 0 , 'POS PROFIT', IIF(PROFIT =0, 'ZERO', 'NEG PROFIT')) AS PROFIT_GRADES
FROM SALES_DATA
ORDER BY PROFIT DESC

-- CASE WHEN COND1 THEN VALUE1 WHEN COND2 THEN VALUE2....ELSE VALUEN END
SELECT SALES,
(CASE WHEN SALES >=10000 THEN 'GRADE A' ELSE 'GRADE B' END) AS GRADES,
(CASE WHEN SALES >=10000 THEN 'GRADE A' WHEN SALES>=4000 THEN 'GRADE B' ELSE 'GRADE C' END) AS GRADES 
FROM SALES_DATA 
ORDER BY SALES DESC

-- MATH FUNCTIONS
SELECT SALES, 
ROUND(SALES, 1) AS ROUND_SALES_1DIGIT,
CEILING(SALES) AS CEIL,
FLOOR(SALES) AS FLR
FROM SALES_DATA

SELECT SALES,(CASE WHEN SALES >=10000 THEN 'GRADE A' ELSE 'GRADE B' END) AS GRADES,(CASE WHEN SALES >=10000 THEN 'GRADE A' WHEN SALES>=4000 THEN 'GRADE B' ELSE 'GRADE C' END) AS GRADES FROM SALES_DATAORDER BY SALES DESC

-- UPDATE JOIN

CREATE TABLE EMP_NEW_SAL
(EMPID	INT, NEW_SAL	NUMERIC(10, 1))

INSERT INTO EMP_NEW_SAL VALUES
(7369,	1200),
(7499,	1450),
(7521,	1700),
(7566,	1950),
(7654,	2200),
(7698,	2450),
(7782,	2700),
(7788,	2950),
(7839,	3200),
(7844,	3450),
(7876,	3700),
(7900,	3950),
(7902,	4200),
(7934,	4450)

UPDATE EMP
SET EMP.SAL = EMP_NEW_SAL.NEW_SAL
FROM EMP INNER JOIN EMP_NEW_SAL ON EMP.EMPNO = EMP_NEW_SAL.EMPID

SELECT * FROM EMP

-- MERGE JOIN

-- WINDOW FUNCTIONS


-- TEMP TABLES
-- CTE
-- VIEWS

